services:
  php:
    container_name: ap.admin
    user: "${UID}:${GID}"
    build:
      context: ./conf/docker-php
      args:
        UID: "${UID}"
        GID: "${GID}"
    environment:
      APPLICATION_ENV: development
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ap_admin
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "127.0.0.1:4102:3306"
  nginx:
    image: nginx:1.18-alpine
    ports:
      - "127.0.0.1:4101:80"
    volumes:
      - .:/app
      - ./conf/nginx.conf.example:/etc/nginx/conf.d/default.conf
    links:
      - php

