services:
  php:
    container_name: ap.admin2
    build: ./conf/docker-php
    environment:
      APPLICATION_ENV: development
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ap_admin2
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3002:3306"
  nginx:
    image: nginx:1.18
    ports:
      - '3001:80'
    volumes:
      - .:/app
      - ./conf/nginx.conf.example:/etc/nginx/conf.d/default.conf
    links:
      - php

